# Generated by Django 5.2.5 on 2025-08-16 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(max_length=20)),
                ('insurer_name', models.CharField(max_length=50)),
                ('discharge_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denial_reason', models.CharField(max_length=200)),
                ('cpt_codes', models.CharField(max_length=200)),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claims_app.claimlist')),
            ],
        ),
    ]
