# Generated by Django 5.2.5 on 2025-08-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdetails',
            name='denial_reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
