# Generated by Django 5.2.5 on 2025-09-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0002_alter_claimdetails_denial_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimlist',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
