# Generated by Django 5.2.5 on 2025-09-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0003_claimlist_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdetails',
            name='flag_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
