# Generated by Django 5.2.5 on 2025-09-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0004_claimdetails_flag_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdetails',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
