# Generated by Django 5.2.5 on 2025-09-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0005_claimdetails_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdetails',
            name='note_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
