# Generated by Django 5.2.5 on 2025-09-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0006_claimdetails_note_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimdetails',
            old_name='claim_id',
            new_name='claim',
        ),
    ]
