# Generated by Django 5.2.5 on 2025-09-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0007_rename_claim_id_claimdetails_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimdetails',
            name='flag_stamp',
        ),
        migrations.RemoveField(
            model_name='claimdetails',
            name='note',
        ),
        migrations.RemoveField(
            model_name='claimdetails',
            name='note_stamp',
        ),
        migrations.RemoveField(
            model_name='claimlist',
            name='flag',
        ),
        migrations.CreateModel(
            name='NotesAndFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('note_stamp', models.DateTimeField(blank=True, null=True)),
                ('flag_stamp', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='claims_app.claimlist')),
            ],
        ),
    ]
