# Generated by Django 5.2.5 on 2025-09-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0008_remove_claimdetails_flag_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesandflags',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_and_flags', to='claims_app.claimlist'),
        ),
    ]
